syntax error1

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -21,16 +21,16 @@ jobs:
       - uses: actions/checkout@v3
       - run: check.sh $(pwd) $(pwd)
       - run: |
-      check.sh $(pwd) $(pwd) 2>&1 | tee coding-style-reports.log
-      if [ -s coding-style-reports.log ]; then
-        cat coding-style-reports.log | while read -r line; do
-        file=$(echo "$line" | cut -d ':' -f1)
-        line_number=$(echo "$line" | cut -d ':' -f2)
-        error_message=$(echo "$line" | cut -d ':' -f3-)
-        echo "::error file=${file},line=${line_number}::${error_message}"
-        done
-      exit 1
-      fi
+           check.sh $(pwd) $(pwd) 2>&1 | tee coding-style-reports.log
+          if [ -s coding-style-reports.log ]; then
+             cat coding-style-reports.log | while read -r line; do
+             file=$(echo "$line" | cut -d ':' -f1)
+             line_number=$(echo "$line" | cut -d ':' -f2)
+             error_message=$(echo "$line" | cut -d ':' -f3-)
+             echo "::error file=${file},line=${line_number}::${error_message}"
+             done
+             exit 1
+          fi
   check_program_compilation:
     name: check_program_compilation
     runs-on: ubuntu-latest
